<?php
/**
 * Styles & scripts. All wp_enqueue_* — no raw <link>/<script> in header.php/footer.php.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * wp_enqueue_script(), version-busted by the file's own mtime (same pattern
 * every script handle here already used individually before 2026-08-06's JS
 * bundle split multiplied the number of handles from 2 to 6) — factored out
 * once repeating it inline for each bundle stopped being the shorter option.
 *
 * 2026-08-06 (JS minification): loads the .min.js sibling generated by
 * `npm run build:js` (scripts/build-js.js, terser --compress --mangle)
 * when one exists and SCRIPT_DEBUG isn't forcing raw sources — same
 * convention WordPress core's own scripts use SCRIPT_DEBUG for. Falls back
 * to the raw, unminified $rel_path whenever either condition doesn't hold,
 * so a bundle with no .min.js yet (or a local dev environment with
 * SCRIPT_DEBUG true) still works exactly as before this change, just
 * unminified.
 */
function itoi_enqueue_versioned_script( $handle, $rel_path, $deps ) {
	$use_min  = ! ( defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG );
	$min_rel  = preg_replace( '/\.js$/', '.min.js', $rel_path );
	$min_path = ITOI_THEME_DIR . '/' . $min_rel;

	$actual_rel = ( $use_min && file_exists( $min_path ) ) ? $min_rel : $rel_path;
	$path       = ITOI_THEME_DIR . '/' . $actual_rel;
	$ver        = file_exists( $path ) ? filemtime( $path ) : ITOI_THEME_VERSION;

	wp_enqueue_script( $handle, ITOI_THEME_URI . '/' . $actual_rel, $deps, $ver, true );
}

function itoi_enqueue_assets() {
	$style_path = ITOI_THEME_DIR . '/assets/css/style.css';
	$style_ver  = file_exists( $style_path ) ? filemtime( $style_path ) : ITOI_THEME_VERSION;

	wp_enqueue_style(
		'itoi-style',
		ITOI_THEME_URI . '/assets/css/style.css',
		array(),
		$style_ver
	);

	// 2026-08-06 (JS bundle split, see NOTES.md/docs/deferred-followups.md):
	// the single assets/js/main.js (100.7KB raw / 29.2KB gzipped by the time
	// of the split) shipped every page's interactivity to every visitor,
	// even though most of it only ever runs on one template. Replaced with
	// 4 smaller bundles, each enqueued only where its markup actually
	// exists — same functions, same behavior, just not downloaded/parsed
	// on pages that never use them. `itoi-core` is the one sitewide bundle
	// (nav, the Finder popup, flip-cards, scroll-reveal, lazy media) and is
	// always registered as a dependency of the other 3, so load order
	// matches the old single-file version exactly.
	itoi_enqueue_versioned_script( 'itoi-core', 'assets/js/core.js', array() );

	// Solution Builder popup handoff (footer.php + initFinder(), now in
	// core.js) — sitewide, since the popup itself is sitewide. Superseded
	// 2026-07-24: this used to localize itoiFinderData (resolved
	// case-study/solution routing for the old inline-results Find Your Fit
	// flow); that routing no longer exists (inc/finder.php deleted, see
	// NOTES.md) — the popup now just needs the destination URL to redirect
	// to after step 7.
	wp_localize_script( 'itoi-core', 'itoiSolutionBuilderConfig', array( 'url' => home_url( '/solution-builder/' ) ) );

	// Mega-hero dot-nav slideshow (PROJECT.md §3 mechanic #2). 2026-07-23:
	// restored after an earlier session incorrectly removed the multi-slide
	// behaviour entirely — this time actually wired to the front end via
	// localize (the field existed before but no template ever read it; see
	// NOTES.md). initHeroSlideshow() (now assets/js/homepage.js) falls back
	// to a small hardcoded array if this is empty, same defensive pattern as
	// the rest of this file, so the hero never renders broken if the
	// options page hasn't been saved yet.
	//
	// 2026-08-05 (external improvement plan Phase 6.3): both this block and
	// the why_choose_photos block below used to run unconditionally on
	// every page — the hero and "Why choose ITOI" markup only exist on
	// front-page.php. 2026-08-06: superseded by the bundle split itself —
	// homepage.js (which reads both) is now only enqueued on the front
	// page at all, so this is_front_page() guard is what makes localizing
	// onto 'itoi-homepage' safe rather than fatal (wp_localize_script on a
	// handle that was never registered silently no-ops, but there'd be
	// nothing to no-op onto correctly without this).
	if ( is_front_page() ) :
	itoi_enqueue_versioned_script( 'itoi-homepage', 'assets/js/homepage.js', array( 'itoi-core' ) );

	// Door Reveal (template-parts/home/hero-door-reveal.php, 2026-09-01) —
	// its own bundle, and deliberately NOT a dependency of itoi-core/
	// itoi-homepage: it's self-contained, it's the only script on the site
	// doing per-scroll-frame work, and this way it's droppable by deleting
	// this one call. Front page only, same as the section itself. No
	// localize — every value it animates is already in the markup.
	itoi_enqueue_versioned_script( 'itoi-door-hero', 'assets/js/door-hero.js', array() );
	$itoi_hero_slides = array();
	if ( function_exists( 'get_field' ) ) {
		$itoi_hero_rows = get_field( 'hero_slides', 'option' );
		if ( is_array( $itoi_hero_rows ) ) {
			foreach ( $itoi_hero_rows as $itoi_hero_row ) {
				$itoi_partner_logo_id = $itoi_hero_row['partner_logo'] ?? 0;
				// Per-slide background photo/video (added 2026-07-23, see
				// NOTES.md) — each slide falls back to the plain gradient
				// independently when its own photo/video is empty, so this
				// is real per-row data, not a single sitewide override.
				$itoi_slide_photo_id  = $itoi_hero_row['photo'] ?? 0;
				$itoi_slide_video     = $itoi_hero_row['video'] ?? null;
				$itoi_hero_slides[]   = array(
						// esc_html()/esc_url() here (2026-08-10 pentest fix) — these
						// values are inserted client-side via innerHTML/attribute
						// concatenation (assets/js/homepage.js), not textContent, so
						// they need pre-escaping the same way template-parts/home/
						// why-choose.php already escapes this exact data server-side.
						// `edit_posts` (any Contributor+) can edit these fields via
						// the Site Settings options page — see inc/acf.php.
						'headline'      => esc_html( $itoi_hero_row['headline'] ?? '' ),
						'subcopy'       => esc_html( $itoi_hero_row['subcopy'] ?? '' ),
						'isPartnership' => ! empty( $itoi_hero_row['is_partnership'] ),
						'partnerName'   => esc_html( $itoi_hero_row['partner_name'] ?? '' ),
						'partnerLogo'   => $itoi_partner_logo_id ? esc_url( wp_get_attachment_image_url( $itoi_partner_logo_id, 'medium' ) ) : '',
						'photo'         => $itoi_slide_photo_id ? esc_url( wp_get_attachment_image_url( $itoi_slide_photo_id, 'large' ) ) : '',
						'photoAlt'      => $itoi_slide_photo_id ? esc_html( get_post_meta( $itoi_slide_photo_id, '_wp_attachment_image_alt', true ) ?: '' ) : '',
						'video'         => ! empty( $itoi_slide_video['url'] ) ? esc_url( $itoi_slide_video['url'] ) : '',
					);
			}
		}
	}
	wp_localize_script( 'itoi-homepage', 'itoiHeroSlides', $itoi_hero_slides );

	// Trust & Stats section (template-parts/home/trust-credibility.php) —
	// the editor's picked clients (Site Settings ▸ Trust & Stats ▸ "Client
	// logos shown", trust_logo_clients) in their chosen order, or every
	// published `client` post ordered `title ASC` when nothing is picked.
	// Either way this matches that template's own initial 6-client query
	// exactly, so the first chunk here lines up with what's server-rendered
	// and there's no visual jump on the first rotation. initTrustLogoRotation()
	// (homepage.js) cycles through the rest, 6 at a time, fading the row
	// between chunks — real content, not a canned demo loop. Real `logo`
	// image if a client has one uploaded, matching itoi_trust_logo_mark()'s
	// own fallback-to-text-wordmark logic exactly so a JS-swapped chunk
	// looks identical to a server-rendered one.
	$itoi_trust_clients = array();
	if ( function_exists( 'get_field' ) ) {
		$itoi_trust_client_args = array(
			'post_type'      => 'client',
			'post_status'    => 'publish',
			'posts_per_page' => -1,
			'orderby'        => 'title',
			'order'          => 'ASC',
		);
		$itoi_trust_logo_ids = get_field( 'trust_logo_clients', 'option' );
		if ( ! empty( $itoi_trust_logo_ids ) ) {
			$itoi_trust_client_args['post__in'] = array_map( 'intval', (array) $itoi_trust_logo_ids );
			$itoi_trust_client_args['orderby']  = 'post__in';
			unset( $itoi_trust_client_args['order'] );
		}
		$itoi_trust_client_posts = get_posts( $itoi_trust_client_args );
		foreach ( $itoi_trust_client_posts as $itoi_tc_post ) {
			$itoi_tc_logo_id  = get_field( 'logo', $itoi_tc_post->ID );
			$itoi_tc_logo_url = $itoi_tc_logo_id ? wp_get_attachment_image_url( $itoi_tc_logo_id, 'medium' ) : '';
			$itoi_trust_clients[] = array(
				'name' => esc_html( get_the_title( $itoi_tc_post ) ),
				'logo' => $itoi_tc_logo_url ? esc_url( $itoi_tc_logo_url ) : '',
			);
		}
	}
	wp_localize_script( 'itoi-homepage', 'itoiTrustClients', $itoi_trust_clients );

	// Trust & Stats stat-card grid (template-parts/home/trust-credibility.php)
	// — every configured metric via itoi_get_trust_metrics() (inc/trust.php),
	// not just the first 4 shown server-side. That function already applies
	// the same empty-repeater fallback the template used to inline, so this
	// list and the template's own first-4 slice can never drift apart.
	// initTrustMetricsRotation() (homepage.js) cross-fades the grid through
	// the rest, 4 at a time — same pattern/cadence as the client-logo row
	// above (itoiTrustClients).
	$itoi_trust_metrics_js = array();
	if ( function_exists( 'itoi_get_trust_metrics' ) ) {
		foreach ( itoi_get_trust_metrics() as $itoi_tm_row ) {
			$itoi_trust_metrics_js[] = array(
				'value' => esc_html( $itoi_tm_row['stat_value'] ?? '' ),
				'label' => esc_html( $itoi_tm_row['stat_label'] ?? '' ),
			);
		}
	}
	wp_localize_script( 'itoi-homepage', 'itoiTrustMetrics', $itoi_trust_metrics_js );

	// "Why choose ITOI" split-panel (PROJECT.md §3 mechanic #6) — one row per
	// pill tab, same order as front-page.php's #pillTabs. Fully ACF-driven as
	// of 2026-08-04 (see NOTES.md) — used to be photo/video only, with the
	// title/description/bullets/CTA hardcoded in main.js's old `whyData`
	// array; that array is gone, this is now the only source, for both the
	// server-rendered tab 0 (front-page.php) and every tab-click swap
	// (initWhyChooseTabs() in main.js). Video takes priority over photo when
	// both are set, same convention as itoiHeroSlides above; photo also
	// doubles as the video's poster/reduce-motion fallback.
	$itoi_why_tabs = array();
	if ( function_exists( 'get_field' ) ) {
		$itoi_why_rows = get_field( 'why_choose_photos', 'option' );
		if ( is_array( $itoi_why_rows ) ) {
			foreach ( $itoi_why_rows as $itoi_why_row ) {
				$itoi_why_photo_id = $itoi_why_row['photo'] ?? 0;
				$itoi_why_video    = $itoi_why_row['video'] ?? null;
				$itoi_why_bullets  = array();
				foreach ( (array) ( $itoi_why_row['bullets'] ?? array() ) as $itoi_why_bullet_row ) {
					if ( ! empty( $itoi_why_bullet_row['text'] ) ) {
						$itoi_why_bullets[] = esc_html( $itoi_why_bullet_row['text'] );
					}
				}
				$itoi_why_tabs[] = array(
					// esc_html()/esc_url() here (2026-08-10 pentest fix) — see the
					// itoiHeroSlides comment above for why.
					'tabLabel'    => esc_html( $itoi_why_row['tab_label'] ?? '' ),
					'title'       => esc_html( $itoi_why_row['title'] ?? '' ),
					'description' => esc_html( $itoi_why_row['description'] ?? '' ),
					'bullets'     => $itoi_why_bullets,
					'ctaLabel'    => esc_html( $itoi_why_row['cta_label'] ?? '' ),
					'ctaUrl'      => esc_url( $itoi_why_row['cta_url'] ?? '#' ),
					'photo'       => $itoi_why_photo_id ? esc_url( wp_get_attachment_image_url( $itoi_why_photo_id, 'large' ) ) : '',
					'video'       => ! empty( $itoi_why_video['url'] ) ? esc_url( $itoi_why_video['url'] ) : '',
				);
			}
		}
	}
	wp_localize_script( 'itoi-homepage', 'itoiWhyTabs', $itoi_why_tabs );
	endif; // is_front_page()

	// The 7 per-industry interactive mechanics + long-form sub-nav —
	// single-industry.php only. is_singular('industry') rather than a
	// template-file check for the same reason as the solution-builder
	// slug match below: this CPT's single template comes from the
	// single-{post_type}.php hierarchy fallback, not a user-assigned
	// template with its own meta value.
	if ( is_singular( 'industry' ) ) {
		itoi_enqueue_versioned_script( 'itoi-industry-simulators', 'assets/js/industry-simulators.js', array( 'itoi-core' ) );
	}

	// Listing-page filter pills — page-portfolio.php, archive-guide.php,
	// page-use-cases.php, and the 3 Education Hub pages (Glossary/FAQ/hub
	// landing). One shared bundle (listing-filters.js) since each page's
	// filter function guards on its own element IDs and only one ever
	// matches per page — see that file's own header comment.
	if ( is_page( array( 'portfolio', 'use-cases', 'glossary', 'education', 'faq' ) ) || is_post_type_archive( 'guide' ) ) {
		itoi_enqueue_versioned_script( 'itoi-listing-filters', 'assets/js/listing-filters.js', array( 'itoi-core' ) );
	}

	// Solution Builder (/solution-builder/) — its own script, only loaded on
	// that page rather than folded into a shared bundle, since the
	// multi-step engine/print-proposal logic is sizeable and page-specific.
	// Matched by slug, not is_page_template(): that page's template comes
	// from the page-{slug}.php hierarchy fallback with no _wp_page_template
	// meta set, which is_page_template() can't see (it only reads that meta
	// value).
	if ( is_page( 'solution-builder' ) ) {
		itoi_enqueue_versioned_script( 'itoi-solution-builder', 'assets/js/solution-builder.js', array() );

		wp_localize_script(
			'itoi-solution-builder',
			'itoiSolutionBuilder',
			array(
				'ajaxUrl' => admin_url( 'admin-ajax.php' ),
				'nonce'   => wp_create_nonce( 'itoi_solution_builder' ),
			)
		);
	}
}
add_action( 'wp_enqueue_scripts', 'itoi_enqueue_assets' );

/**
 * Preload the two most widely-used Lora weights (400 body, 700 headings —
 * every template uses both above the fold; font-extrabold/800 text also
 * resolves to this same 700 file, see its @font-face's 700-900 weight
 * range in src/tailwind.css). Paired with font-display: optional there:
 * preloading gives the real font the best chance of being ready before
 * that swap-decision window closes, so most visits still render Lora on
 * the first paint rather than falling back. Was Inter's 400/800 files
 * until the 2026-08-21 sitewide font swap — see src/tailwind.css's Lora
 * @font-face block for the full rationale.
 */
function itoi_preload_fonts() {
	$itoi_fonts = array( 'lora-latin-400-normal.woff2', 'lora-latin-700-normal.woff2' );
	foreach ( $itoi_fonts as $itoi_font_file ) {
		printf(
			'<link rel="preload" href="%s" as="font" type="font/woff2" crossorigin>' . "\n",
			esc_url( ITOI_THEME_URI . '/assets/fonts/' . $itoi_font_file )
		);
	}
}
add_action( 'wp_head', 'itoi_preload_fonts', 1 );

/**
 * Sitewide default loading="lazy" for wp_get_attachment_image() output
 * (2026-08-05 performance pass, see NOTES.md — move 2 of "close the
 * Lighthouse gap") — explicit and deterministic, rather than relying on
 * core's own first-N-images heuristic (wp_get_loading_optimization_attributes()),
 * whose counter resets per request and doesn't reliably know which
 * wp_get_attachment_image() call is "above the fold" across this theme's
 * varied templates. Only sets it when nothing already specified `loading`
 * — the one call site that needs eager loading (the mega-hero's LCP photo,
 * front-page.php) passes loading="eager" explicitly in its own $attr
 * array, which is already merged into $attr by the time this filter runs,
 * so the `empty()` check correctly leaves it alone.
 */
function itoi_default_lazy_loading_attr( $attr ) {
	if ( empty( $attr['loading'] ) ) {
		$attr['loading'] = 'lazy';
	}
	return $attr;
}
add_filter( 'wp_get_attachment_image_attributes', 'itoi_default_lazy_loading_attr' );
