<?php
/**
 * SEO meta tags and structured data — Yoast fallbacks and custom schema
 * for CPTs. inc/schema.php is the source of truth for structured data
 * (LocalBusiness/Service/Article/Product/BreadcrumbList/etc.) — this file
 * covers everything else: meta description, Open Graph/Twitter image,
 * canonical URLs, robots meta, archive titles/descriptions, pagination
 * rel links, the sitemap fallback, and robots.txt.
 *
 * Yoast SEO (free) is active on this site (confirmed: WPSEO_VERSION
 * defined, WPSEO_Meta class exists) and already handles the baseline for
 * standard posts/pages — every function below either (a) fills a gap
 * Yoast free doesn't cover for this theme's CPTs, or (b) provides a
 * fallback via Yoast's own filters ONLY when Yoast hasn't already set a
 * value, never overriding an explicit editor-set value. Every function
 * that can run standalone (no Yoast installed) checks
 * `defined( 'WPSEO_VERSION' )` first and only outputs directly when Yoast
 * is genuinely absent — this theme is not assumed to run without Yoast,
 * but shouldn't emit broken/duplicate markup if it ever does.
 *
 * All values are sourced from ACF fields or core post data. If a field is
 * empty, functions here return/output nothing for that piece — never
 * invented copy (PROJECT.md §6).
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// ---------------------------------------------------------------
// Meta description fallback
// ---------------------------------------------------------------

/**
 * Resolves a meta description for the current request from ACF/post data
 * only — the single source both the Yoast-fallback filter and the
 * no-Yoast direct-output path below read from, so there's one place that
 * defines "what is this page's description," not two that could drift.
 *
 * Field per post type matches this theme's own established convention
 * (see inc/schema.php's itoi_article_schema()/itoi_guide_schema() — case
 * studies use `headline`, not `dek`, everything else uses `dek`).
 */
function itoi_seo_resolve_description() {
	if ( is_front_page() ) {
		// No standalone `hero_subcopy` option field exists — the hero's
		// subcopy is slide 0's `subcopy` sub-field inside the
		// `hero_slides` repeater (see template-parts/home/hero.php), so
		// that's what's actually read here instead of a field name that
		// was never real.
		$slides = get_field( 'hero_slides', 'option' );
		if ( ! empty( $slides[0]['subcopy'] ) ) {
			return $slides[0]['subcopy'];
		}
		return '';
	}

	if ( ! is_singular() ) {
		return '';
	}

	$post_id   = get_the_ID();
	$post_type = get_post_type( $post_id );

	if ( ! $post_id ) {
		return '';
	}

	$dek_field_by_post_type = array(
		'solution'   => 'dek',
		'product'    => 'dek',
		'industry'   => 'dek',
		'case_study' => 'headline', // case studies use 'headline', not 'dek'
		'insight'    => 'dek',
		'guide'      => 'dek',
		'page'       => 'dek',
	);

	if ( isset( $dek_field_by_post_type[ $post_type ] ) ) {
		$value = get_field( $dek_field_by_post_type[ $post_type ], $post_id );
		if ( $value ) {
			return $value;
		}
	}

	// Final fallback: the post's own excerpt (custom or auto-generated by
	// WordPress from the content), trimmed to a word boundary near the
	// ~155-char length search engines actually use.
	$excerpt = get_the_excerpt( $post_id );
	if ( $excerpt ) {
		return wp_html_excerpt( wp_strip_all_tags( $excerpt ), 155, '…' );
	}

	return '';
}

/**
 * Yoast fallback — only supplies a description when Yoast's own value
 * (editor-set meta box, or Yoast's own auto-generated fallback) is empty.
 * Never overrides a value Yoast already produced.
 */
function itoi_seo_metadesc_fallback( $metadesc ) {
	if ( $metadesc ) {
		return $metadesc;
	}
	return itoi_seo_resolve_description();
}
if ( defined( 'WPSEO_VERSION' ) ) {
	add_filter( 'wpseo_metadesc', 'itoi_seo_metadesc_fallback' );
}

/**
 * No-Yoast direct output — only runs if Yoast genuinely isn't installed
 * (this theme assumes it is; this is a graceful-degradation path, not the
 * primary mechanism). Priority 20 keeps it well after anything else that
 * might output head meta first.
 */
function itoi_seo_output_metadesc_no_yoast() {
	if ( defined( 'WPSEO_VERSION' ) ) {
		return;
	}
	$description = itoi_seo_resolve_description();
	if ( $description ) {
		echo '<meta name="description" content="' . esc_attr( $description ) . '">' . "\n";
	}
}
add_action( 'wp_head', 'itoi_seo_output_metadesc_no_yoast', 20 );

// ---------------------------------------------------------------
// Open Graph / Twitter share-image fallback
// ---------------------------------------------------------------

/**
 * Resolves a fallback share-image attachment ID for the current singular
 * post from ACF fields — never invents an image. Priority: hero_image
 * (the real hero-photo field on case_study/industry/etc.) -> hero_photo
 * (reserved; no CPT uses this field name today, kept as a real forward-
 * compatible check, same convention as inc/schema.php's dek/
 * product_price checks). The site-wide tier — Site Settings' own default
 * image, used when a post has neither a featured image nor either ACF
 * field — is Yoast's own `og_default_image_id` option, which Yoast
 * already applies automatically once nothing else is found (see
 * Open_Graph_Image_Generator::add_from_default() in the plugin itself);
 * not reimplemented here to avoid a second, competing fallback path.
 */
function itoi_seo_resolve_share_image_id( $post_id ) {
	$hero_image_id = get_field( 'hero_image', $post_id );
	if ( $hero_image_id ) {
		return (int) $hero_image_id;
	}

	$hero_photo_id = get_field( 'hero_photo', $post_id );
	if ( $hero_photo_id ) {
		return (int) $hero_photo_id;
	}

	return 0;
}

/**
 * Adds an ACF-sourced image to Yoast's Open Graph image container — only
 * when the post has no WP featured image of its own. `wpseo_add_
 * opengraph_images` fires before Yoast's own indexable-based detection,
 * which unconditionally adds the featured image if one exists regardless
 * of what's already in the container — the has_post_thumbnail() guard is
 * what stops that step from then adding a second, competing image on top
 * of this one.
 *
 * No separate Twitter-image fallback: Yoast's own generate_twitter_image()
 * deliberately returns an empty string whenever Open Graph is enabled and
 * has at least one image, explicitly "letting the Open Graph tags handle
 * the rest of the fallback hierarchy" (its own source comment) — Twitter
 * reads og:image itself when twitter:image is absent, so fixing the
 * og:image gap here already fixes Twitter Card sharing too, with no
 * separate wpseo_twitter_image hook needed.
 *
 * Both wpseo_opengraph_image and wpseo_twitter_image (the filters the
 * task named) were tried first and found unusable for this: Yoast only
 * calls either filter once per image already present in its own image
 * list — with zero images found, the filter never fires at all, so it
 * can modify an existing choice but can't add one from nothing. Confirmed
 * by reading wp-content/plugins/wordpress-seo/src/presenters/open-graph/
 * image-presenter.php directly rather than assuming the filter name in
 * the task description was the right integration point.
 */
function itoi_seo_add_opengraph_image_fallback( $image_container ) {
	if ( ! is_singular() ) {
		return;
	}
	$post_id = get_the_ID();
	if ( ! $post_id || has_post_thumbnail( $post_id ) ) {
		return;
	}
	$image_id = itoi_seo_resolve_share_image_id( $post_id );
	if ( $image_id ) {
		$image_container->add_image_by_id( $image_id );
	}
}
if ( defined( 'WPSEO_VERSION' ) ) {
	add_action( 'wpseo_add_opengraph_images', 'itoi_seo_add_opengraph_image_fallback' );
}

// ---------------------------------------------------------------
// Canonical URL — paginated CPT archives
// ---------------------------------------------------------------

/**
 * Every CPT archive template in this theme (archive-solution.php,
 * archive-product.php, archive-industry.php, archive-case_study.php,
 * archive-insight.php, archive-guide.php) runs its own
 * `posts_per_page => -1` query, ignoring WordPress's own pagination
 * entirely — every item always renders on the first page. The *main*
 * query (which is what actually governs is_paged()/max_num_pages/whether
 * /page/2/ 404s) still uses the site's default posts_per_page (10) —
 * confirmed live: a CPT with more than 10 items gets a real, 200-
 * responding /page/2/ that renders the exact same full list as page 1
 * (`/education/guides/page/2/`, 15 real guides, same 15 on both URLs) —
 * genuine duplicate content, not a hypothetical one. Canonicalizing every
 * paginated CPT-archive request back to its clean, unpaginated URL closes
 * that gap without touching the archive templates' own querying (out of
 * scope for a canonical tag to fix, and there's a real reason each one
 * intentionally shows everything on one page — see NOTES.md).
 *
 * The client-side listing-page filters (listing-filters.js, on
 * page-customers.php/page-use-cases.php/page-faq.php/page-glossary.php/
 * page-education.php) don't create a second URL at all — the filtering
 * never changes the URL, so there's no separate address for a search
 * engine to index in the first place; nothing to canonicalize there.
 */
function itoi_seo_canonical_paginated_archive( $canonical ) {
	if ( ! is_post_type_archive() || ! is_paged() ) {
		return $canonical;
	}
	$post_type    = get_query_var( 'post_type' );
	$archive_link = is_array( $post_type ) ? '' : get_post_type_archive_link( $post_type );
	return $archive_link ? $archive_link : $canonical;
}
if ( defined( 'WPSEO_VERSION' ) ) {
	add_filter( 'wpseo_canonical', 'itoi_seo_canonical_paginated_archive' );
}

/**
 * No-Yoast direct canonical output for CPT archives — WP core's own
 * rel_canonical() (wp-includes/link-template.php, on wp_head by default)
 * only fires for is_singular(), never for archives, with or without
 * Yoast, so this doesn't duplicate anything core already outputs. Covers
 * every archive page, not just paginated ones — page 1 canonicalizing to
 * itself is harmless and correct, and it means this doesn't need its own
 * separate is_paged() branch.
 */
function itoi_seo_output_canonical_no_yoast() {
	if ( defined( 'WPSEO_VERSION' ) || ! is_post_type_archive() ) {
		return;
	}
	$post_type    = get_query_var( 'post_type' );
	$archive_link = is_array( $post_type ) ? '' : get_post_type_archive_link( $post_type );
	if ( $archive_link ) {
		echo '<link rel="canonical" href="' . esc_url( $archive_link ) . '">' . "\n";
	}
}
add_action( 'wp_head', 'itoi_seo_output_canonical_no_yoast', 5 );

// ---------------------------------------------------------------
// Robots meta — noindex for Solution Builder, 404, and search
// ---------------------------------------------------------------

/**
 * Every public CPT archive/single and standard WP Page is deliberately
 * NOT in this list — only these 3 genuinely shouldn't be indexed: the
 * Solution Builder quiz/tool (not content that should rank on its own),
 * 404s, and internal search results.
 */
function itoi_seo_should_noindex() {
	return is_404() || is_search() || is_page( 'solution-builder' );
}

/**
 * Yoast robots filter — `wpseo_robots` receives and expects back a
 * formatted string like "index, follow, max-snippet:-1, ..." (confirmed
 * by reading Indexable_Presentation::filter_robots() in the plugin
 * itself), not an array. Swaps the leading `index` token for `noindex`;
 * leaves `follow` (and everything else Yoast already computed) alone —
 * noindex,follow is the correct combination for all 3 pages here (a
 * quiz tool, a 404, a search results page can all still have real
 * navigation links worth letting search engines follow; only the page
 * itself shouldn't rank), not just the Solution Builder case the task
 * specifically named "noindex,follow" for.
 */
function itoi_seo_robots_noindex_filter( $robots ) {
	if ( ! itoi_seo_should_noindex() ) {
		return $robots;
	}
	$parts = array_filter(
		array_map( 'trim', explode( ',', $robots ) ),
		function ( $part ) {
			return 'index' !== $part;
		}
	);
	array_unshift( $parts, 'noindex' );
	return implode( ', ', $parts );
}
if ( defined( 'WPSEO_VERSION' ) ) {
	add_filter( 'wpseo_robots', 'itoi_seo_robots_noindex_filter' );
}

function itoi_seo_output_robots_no_yoast() {
	if ( defined( 'WPSEO_VERSION' ) || ! itoi_seo_should_noindex() ) {
		return;
	}
	echo '<meta name="robots" content="noindex,follow">' . "\n";
}
add_action( 'wp_head', 'itoi_seo_output_robots_no_yoast', 1 );

// ---------------------------------------------------------------
// CPT archive title/description fallbacks
// ---------------------------------------------------------------

/**
 * Fallback title/description per CPT archive — only used when Yoast
 * hasn't already been configured with something real for that archive.
 *
 * Checking whether the wpseo_title/wpseo_metadesc *filter's own output*
 * is empty (the task's own suggested approach) doesn't actually work
 * here: Yoast auto-populates every unconfigured CPT archive title with
 * its own generic template ('%%pt_plural%% Archive %%page%% %%sep%%
 * %%sitename%%', confirmed by reading Yoast_Option_Titles's own
 * $enriched_defaults in wp-content/plugins/wordpress-seo/inc/options/
 * class-wpseo-option-titles.php) — so the rendered title is never
 * actually an empty string to detect. Checked live before writing this
 * (2026-08-06): solution/industry/case_study/guide archives already have
 * a real custom title AND metadesc configured in the raw wpseo_titles
 * option; product/insight only had Yoast's own generic template (title)
 * and a genuinely empty string (metadesc). itoi_seo_archive_is_configured()
 * below reads that raw option directly instead of trusting the filtered
 * output, so the fallback only replaces an archive that's truly never
 * been set up, not one Yoast has merely rendered its own default for.
 *
 * Titles match the exact copy this fix's own spec named; descriptions
 * are new, kept purely to "what this page lists" — no performance/
 * capability claims invented for a page that's just a listing
 * (PROJECT.md §6).
 */
function itoi_seo_archive_fallbacks() {
	return array(
		'solution'   => array(
			'title'       => 'ITOI Solutions — Vision Systems for Retail, Venues & Security',
			'description' => "Explore ITOI's vision, security and analytics solutions for retail, hospitality, banking, government and more.",
		),
		'product'    => array(
			'title'       => 'ITOI Products — Sensors, Hardware & Devices',
			'description' => "Browse ITOI's hardware — cameras, sensors and edge devices — that power the ITOI platform.",
		),
		'industry'   => array(
			'title'       => 'ITOI Industries — Sector-Specific Solutions',
			'description' => "See how ITOI's platform adapts to retail, hospitality, banking, government and other industries.",
		),
		'case_study' => array(
			'title'       => 'ITOI Case Studies — Customer Success Stories',
			'description' => 'Real ITOI deployments across retail, government and banking — see how customers use the platform.',
		),
		'insight'    => array(
			'title'       => 'ITOI Insights — Articles & Industry Analysis',
			'description' => 'Articles and analysis on vision systems, security and operations from the ITOI team.',
		),
		'guide'      => array(
			'title'       => 'ITOI Guides — Education Hub',
			'description' => "Plain-language guides to ITOI's platform and the technology behind it, from the Education Hub.",
		),
	);
}

/**
 * The current request's archive fallback row, or null if this isn't one
 * of the 6 public CPT archives this covers.
 */
function itoi_seo_current_archive_fallback() {
	if ( ! is_post_type_archive() ) {
		return null;
	}
	$post_type = get_query_var( 'post_type' );
	if ( is_array( $post_type ) ) {
		return null;
	}
	$fallbacks = itoi_seo_archive_fallbacks();
	return isset( $fallbacks[ $post_type ] ) ? array( $post_type, $fallbacks[ $post_type ] ) : null;
}

/**
 * True only when Yoast's raw wpseo_titles option has a real, explicitly-
 * saved value for this archive's title — not Yoast's own auto-populated
 * generic placeholder (see the doc comment above). `%%` is the marker:
 * Yoast's un-replaced replace-var tokens (%%pt_plural%%, %%sitename%%,
 * etc.) only ever appear in its own unconfigured defaults; nobody hand-
 * types that syntax into a real custom title.
 */
function itoi_seo_archive_title_is_configured( $post_type ) {
	$titles_option = get_option( 'wpseo_titles' );
	$value         = isset( $titles_option[ 'title-ptarchive-' . $post_type ] ) ? $titles_option[ 'title-ptarchive-' . $post_type ] : '';
	return '' !== $value && false === strpos( $value, '%%' );
}

/** Same check for the metadesc side — Yoast's default there is genuinely an empty string, so this one IS a plain emptiness check. */
function itoi_seo_archive_metadesc_is_configured( $post_type ) {
	$titles_option = get_option( 'wpseo_titles' );
	$value         = isset( $titles_option[ 'metadesc-ptarchive-' . $post_type ] ) ? $titles_option[ 'metadesc-ptarchive-' . $post_type ] : '';
	return '' !== $value;
}

function itoi_seo_archive_title_fallback( $title ) {
	$current = itoi_seo_current_archive_fallback();
	if ( ! $current ) {
		return $title;
	}
	list( $post_type, $fallback ) = $current;
	if ( ! defined( 'WPSEO_VERSION' ) || ! itoi_seo_archive_title_is_configured( $post_type ) ) {
		return $fallback['title'];
	}
	return $title;
}
if ( defined( 'WPSEO_VERSION' ) ) {
	add_filter( 'wpseo_title', 'itoi_seo_archive_title_fallback' );
} else {
	// document_title_parts (WP 4.4+) — the modern replacement for the
	// old wp_title filter, which core itself has deprecated in favour of
	// this since WordPress no longer calls wp_title() in its own
	// wp_head output.
	add_filter(
		'document_title_parts',
		function ( $parts ) {
			$parts['title'] = itoi_seo_archive_title_fallback( $parts['title'] ?? '' );
			return $parts;
		}
	);
}

function itoi_seo_archive_metadesc_fallback( $metadesc ) {
	$current = itoi_seo_current_archive_fallback();
	if ( ! $current ) {
		return $metadesc;
	}
	list( $post_type, $fallback ) = $current;
	if ( ! defined( 'WPSEO_VERSION' ) || ! itoi_seo_archive_metadesc_is_configured( $post_type ) ) {
		return $fallback['description'];
	}
	return $metadesc;
}
if ( defined( 'WPSEO_VERSION' ) ) {
	add_filter( 'wpseo_metadesc', 'itoi_seo_archive_metadesc_fallback' );
} else {
	add_action(
		'wp_head',
		function () {
			$current = itoi_seo_current_archive_fallback();
			if ( $current ) {
				echo '<meta name="description" content="' . esc_attr( $current[1]['description'] ) . '">' . "\n";
			}
		},
		20
	);
}
