<?php
/**
 * SEO meta tags and structured data — Yoast fallbacks and custom schema
 * for CPTs. inc/schema.php is the source of truth for structured data
 * (LocalBusiness/Service/Article/Product/BreadcrumbList/etc.) — this file
 * covers everything else: meta description, Open Graph/Twitter image,
 * canonical URLs, robots meta, archive titles/descriptions, pagination
 * rel links, the sitemap fallback, and robots.txt.
 *
 * Yoast SEO (free) is active on this site (confirmed: WPSEO_VERSION
 * defined, WPSEO_Meta class exists) and already handles the baseline for
 * standard posts/pages — every function below either (a) fills a gap
 * Yoast free doesn't cover for this theme's CPTs, or (b) provides a
 * fallback via Yoast's own filters ONLY when Yoast hasn't already set a
 * value, never overriding an explicit editor-set value. Every function
 * that can run standalone (no Yoast installed) checks
 * `defined( 'WPSEO_VERSION' )` first and only outputs directly when Yoast
 * is genuinely absent — this theme is not assumed to run without Yoast,
 * but shouldn't emit broken/duplicate markup if it ever does.
 *
 * All values are sourced from ACF fields or core post data. If a field is
 * empty, functions here return/output nothing for that piece — never
 * invented copy (PROJECT.md §6).
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// ---------------------------------------------------------------
// Meta description fallback
// ---------------------------------------------------------------

/**
 * Resolves a meta description for the current request from ACF/post data
 * only — the single source both the Yoast-fallback filter and the
 * no-Yoast direct-output path below read from, so there's one place that
 * defines "what is this page's description," not two that could drift.
 *
 * Field per post type matches this theme's own established convention
 * (see inc/schema.php's itoi_article_schema()/itoi_guide_schema() — case
 * studies use `headline`, not `dek`, everything else uses `dek`).
 */
function itoi_seo_resolve_description() {
	if ( is_front_page() ) {
		// No standalone `hero_subcopy` option field exists — the hero's
		// subcopy is slide 0's `subcopy` sub-field inside the
		// `hero_slides` repeater (see template-parts/home/hero.php), so
		// that's what's actually read here instead of a field name that
		// was never real.
		$slides = get_field( 'hero_slides', 'option' );
		if ( ! empty( $slides[0]['subcopy'] ) ) {
			return $slides[0]['subcopy'];
		}
		return '';
	}

	if ( ! is_singular() ) {
		return '';
	}

	$post_id   = get_the_ID();
	$post_type = get_post_type( $post_id );

	if ( ! $post_id ) {
		return '';
	}

	$dek_field_by_post_type = array(
		'solution'   => 'dek',
		'product'    => 'dek',
		'industry'   => 'dek',
		'case_study' => 'headline', // case studies use 'headline', not 'dek'
		'insight'    => 'dek',
		'guide'      => 'dek',
		'page'       => 'dek',
	);

	if ( isset( $dek_field_by_post_type[ $post_type ] ) ) {
		$value = get_field( $dek_field_by_post_type[ $post_type ], $post_id );
		if ( $value ) {
			return $value;
		}
	}

	// Final fallback: the post's own excerpt (custom or auto-generated by
	// WordPress from the content), trimmed to a word boundary near the
	// ~155-char length search engines actually use.
	$excerpt = get_the_excerpt( $post_id );
	if ( $excerpt ) {
		return wp_html_excerpt( wp_strip_all_tags( $excerpt ), 155, '…' );
	}

	return '';
}

/**
 * Yoast fallback — only supplies a description when Yoast's own value
 * (editor-set meta box, or Yoast's own auto-generated fallback) is empty.
 * Never overrides a value Yoast already produced.
 */
function itoi_seo_metadesc_fallback( $metadesc ) {
	if ( $metadesc ) {
		return $metadesc;
	}
	return itoi_seo_resolve_description();
}
if ( defined( 'WPSEO_VERSION' ) ) {
	add_filter( 'wpseo_metadesc', 'itoi_seo_metadesc_fallback' );
}

/**
 * No-Yoast direct output — only runs if Yoast genuinely isn't installed
 * (this theme assumes it is; this is a graceful-degradation path, not the
 * primary mechanism). Priority 20 keeps it well after anything else that
 * might output head meta first.
 */
function itoi_seo_output_metadesc_no_yoast() {
	if ( defined( 'WPSEO_VERSION' ) ) {
		return;
	}
	$description = itoi_seo_resolve_description();
	if ( $description ) {
		echo '<meta name="description" content="' . esc_attr( $description ) . '">' . "\n";
	}
}
add_action( 'wp_head', 'itoi_seo_output_metadesc_no_yoast', 20 );
