<?php
/**
 * SEO meta tags and structured data — Yoast fallbacks and custom schema
 * for CPTs. inc/schema.php is the source of truth for structured data
 * (LocalBusiness/Service/Article/Product/BreadcrumbList/etc.) — this file
 * covers everything else: meta description, Open Graph/Twitter image,
 * canonical URLs, robots meta, archive titles/descriptions, pagination
 * rel links, the sitemap fallback, and robots.txt.
 *
 * Yoast SEO (free) is active on this site (confirmed: WPSEO_VERSION
 * defined, WPSEO_Meta class exists) and already handles the baseline for
 * standard posts/pages — every function below either (a) fills a gap
 * Yoast free doesn't cover for this theme's CPTs, or (b) provides a
 * fallback via Yoast's own filters ONLY when Yoast hasn't already set a
 * value, never overriding an explicit editor-set value. Every function
 * that can run standalone (no Yoast installed) checks
 * `defined( 'WPSEO_VERSION' )` first and only outputs directly when Yoast
 * is genuinely absent — this theme is not assumed to run without Yoast,
 * but shouldn't emit broken/duplicate markup if it ever does.
 *
 * All values are sourced from ACF fields or core post data. If a field is
 * empty, functions here return/output nothing for that piece — never
 * invented copy (PROJECT.md §6).
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// ---------------------------------------------------------------
// Meta description fallback
// ---------------------------------------------------------------

/**
 * Resolves a meta description for the current request from ACF/post data
 * only — the single source both the Yoast-fallback filter and the
 * no-Yoast direct-output path below read from, so there's one place that
 * defines "what is this page's description," not two that could drift.
 *
 * Field per post type matches this theme's own established convention
 * (see inc/schema.php's itoi_article_schema()/itoi_guide_schema() — case
 * studies use `headline`, not `dek`, everything else uses `dek`).
 */
function itoi_seo_resolve_description() {
	if ( is_front_page() ) {
		// No standalone `hero_subcopy` option field exists — the hero's
		// subcopy is slide 0's `subcopy` sub-field inside the
		// `hero_slides` repeater (see template-parts/home/hero.php), so
		// that's what's actually read here instead of a field name that
		// was never real.
		$slides = get_field( 'hero_slides', 'option' );
		if ( ! empty( $slides[0]['subcopy'] ) ) {
			return $slides[0]['subcopy'];
		}
		return '';
	}

	if ( ! is_singular() ) {
		return '';
	}

	$post_id   = get_the_ID();
	$post_type = get_post_type( $post_id );

	if ( ! $post_id ) {
		return '';
	}

	$dek_field_by_post_type = array(
		'solution'   => 'dek',
		'product'    => 'dek',
		'industry'   => 'dek',
		'case_study' => 'headline', // case studies use 'headline', not 'dek'
		'insight'    => 'dek',
		'guide'      => 'dek',
		'page'       => 'dek',
	);

	if ( isset( $dek_field_by_post_type[ $post_type ] ) ) {
		$value = get_field( $dek_field_by_post_type[ $post_type ], $post_id );
		if ( $value ) {
			return $value;
		}
	}

	// Final fallback: the post's own excerpt (custom or auto-generated by
	// WordPress from the content), trimmed to a word boundary near the
	// ~155-char length search engines actually use.
	$excerpt = get_the_excerpt( $post_id );
	if ( $excerpt ) {
		return wp_html_excerpt( wp_strip_all_tags( $excerpt ), 155, '…' );
	}

	return '';
}

/**
 * Yoast fallback — only supplies a description when Yoast's own value
 * (editor-set meta box, or Yoast's own auto-generated fallback) is empty.
 * Never overrides a value Yoast already produced.
 */
function itoi_seo_metadesc_fallback( $metadesc ) {
	if ( $metadesc ) {
		return $metadesc;
	}
	return itoi_seo_resolve_description();
}
if ( defined( 'WPSEO_VERSION' ) ) {
	add_filter( 'wpseo_metadesc', 'itoi_seo_metadesc_fallback' );
}

/**
 * No-Yoast direct output — only runs if Yoast genuinely isn't installed
 * (this theme assumes it is; this is a graceful-degradation path, not the
 * primary mechanism). Priority 20 keeps it well after anything else that
 * might output head meta first.
 */
function itoi_seo_output_metadesc_no_yoast() {
	if ( defined( 'WPSEO_VERSION' ) ) {
		return;
	}
	$description = itoi_seo_resolve_description();
	if ( $description ) {
		echo '<meta name="description" content="' . esc_attr( $description ) . '">' . "\n";
	}
}
add_action( 'wp_head', 'itoi_seo_output_metadesc_no_yoast', 20 );

// ---------------------------------------------------------------
// Open Graph / Twitter share-image fallback
// ---------------------------------------------------------------

/**
 * Resolves a fallback share-image attachment ID for the current singular
 * post from ACF fields — never invents an image. Priority: hero_image
 * (the real hero-photo field on case_study/industry/etc.) -> hero_photo
 * (reserved; no CPT uses this field name today, kept as a real forward-
 * compatible check, same convention as inc/schema.php's dek/
 * product_price checks). The site-wide tier — Site Settings' own default
 * image, used when a post has neither a featured image nor either ACF
 * field — is Yoast's own `og_default_image_id` option, which Yoast
 * already applies automatically once nothing else is found (see
 * Open_Graph_Image_Generator::add_from_default() in the plugin itself);
 * not reimplemented here to avoid a second, competing fallback path.
 */
function itoi_seo_resolve_share_image_id( $post_id ) {
	$hero_image_id = get_field( 'hero_image', $post_id );
	if ( $hero_image_id ) {
		return (int) $hero_image_id;
	}

	$hero_photo_id = get_field( 'hero_photo', $post_id );
	if ( $hero_photo_id ) {
		return (int) $hero_photo_id;
	}

	return 0;
}

/**
 * Adds an ACF-sourced image to Yoast's Open Graph image container — only
 * when the post has no WP featured image of its own. `wpseo_add_
 * opengraph_images` fires before Yoast's own indexable-based detection,
 * which unconditionally adds the featured image if one exists regardless
 * of what's already in the container — the has_post_thumbnail() guard is
 * what stops that step from then adding a second, competing image on top
 * of this one.
 *
 * No separate Twitter-image fallback: Yoast's own generate_twitter_image()
 * deliberately returns an empty string whenever Open Graph is enabled and
 * has at least one image, explicitly "letting the Open Graph tags handle
 * the rest of the fallback hierarchy" (its own source comment) — Twitter
 * reads og:image itself when twitter:image is absent, so fixing the
 * og:image gap here already fixes Twitter Card sharing too, with no
 * separate wpseo_twitter_image hook needed.
 *
 * Both wpseo_opengraph_image and wpseo_twitter_image (the filters the
 * task named) were tried first and found unusable for this: Yoast only
 * calls either filter once per image already present in its own image
 * list — with zero images found, the filter never fires at all, so it
 * can modify an existing choice but can't add one from nothing. Confirmed
 * by reading wp-content/plugins/wordpress-seo/src/presenters/open-graph/
 * image-presenter.php directly rather than assuming the filter name in
 * the task description was the right integration point.
 */
function itoi_seo_add_opengraph_image_fallback( $image_container ) {
	if ( ! is_singular() ) {
		return;
	}
	$post_id = get_the_ID();
	if ( ! $post_id || has_post_thumbnail( $post_id ) ) {
		return;
	}
	$image_id = itoi_seo_resolve_share_image_id( $post_id );
	if ( $image_id ) {
		$image_container->add_image_by_id( $image_id );
	}
}
if ( defined( 'WPSEO_VERSION' ) ) {
	add_action( 'wpseo_add_opengraph_images', 'itoi_seo_add_opengraph_image_fallback' );
}
